# Generated by Django 5.0.6 on 2024-07-08 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criacao", models.DateTimeField(auto_now_add=True)),
                ("atualizacao", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                ("nome", models.CharField(max_length=100)),
                ("url", models.URLField(unique=True)),
            ],
            options={
                "verbose_name": "nome",
            },
        ),
        migrations.CreateModel(
            name="Dados",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criacao", models.DateTimeField(auto_now_add=True)),
                ("atualizacao", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                ("email", models.EmailField(max_length=254)),
                ("contato", models.TextField(blank=True, default="")),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Usuarios",
                        to="app.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dado",
                "verbose_name_plural": "Dados",
                "unique_together": {("usuario", "email")},
            },
        ),
    ]
